[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/entry/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200
